const TopicByClass = {
  class1: [
    { name: "Xin chào", path: "/class1/Hello", image: "/img/animal.jpg" },
    { name: "Đồ dùng học tập", path: "/class1/school-things", bg: "#b2ff59" },
    { name: "Màu sắc", path: "/class1/colors", bg: "#80d8ff" },
    { name: "Gia đình", path: "/class1/family", bg: "#ff80ab" },
    { name: "Số đếm", path: "/class1/number", bg: "#ff80ab" },
    { name: "Quần áo", path: "/class1/clothes", bg: "#ff80ab" },
    { name: "Ngoại hình", path: "/class1/appearance", bg: "#ff80ab" },
    { name: "Khuôn mặt", path: "/class1/face", bg: "#ff80ab" },
  ],
  class2: [
    { name: "Bữa tiệc sinh nhật", path: "/class2/Birthday party", image: "/img/animal.jpg", },
    { name: "Trong sân", path: "/class2/In the backyard", bg: "#b2ff59" },
    { name: "Vùng nông thôn", path: "/class2/Countryside", bg: "#80d8ff" },
    { name: "Bờ biển", path: "/class2/Seaside", bg: "#ff80ab" },
    { name: "Trang trại", path: "/class2/Farm", bg: "#ffab91" },
    { name: "Nhà bếp", path: "/class2/In the kitchen", bg: "#f48fb1" },
    { name: "Trong làng", path: "/class2/In the village", bg: "#ce93d8" },
    { name: "Cửa hàng tạp hóa", path: "/class2/In the grocery store", bg: "#90caf9", },
  ],
  class3: [
    { name: "Xin chào", path: "/class1/Hello", image: "/img/animal.jpg" },
    { name: "Đồ dùng học tập", path: "/class1/school-things", bg: "#b2ff59" },
    { name: "Màu sắc", path: "/class1/colors", bg: "#80d8ff" },
    { name: "Gia đình", path: "/class1/family", bg: "#ff80ab" },
    { name: "Số đếm", path: "/class1/number", bg: "#ff80ab" },
    { name: "Quần áo", path: "/class1/clothes", bg: "#ff80ab" },
    { name: "Ngoại hình", path: "/class1/appearance", bg: "#ff80ab" },
    { name: "Khuôn mặt", path: "/class1/face", bg: "#ff80ab" },
  ],
  class4: [
    { name: "Xin chào", path: "/class1/Hello", image: "/img/animal.jpg" },
    { name: "Đồ dùng học tập", path: "/class1/school-things", bg: "#b2ff59" },
    { name: "Màu sắc", path: "/class1/colors", bg: "#80d8ff" },
    { name: "Gia đình", path: "/class1/family", bg: "#ff80ab" },
    { name: "Số đếm", path: "/class1/number", bg: "#ff80ab" },
    { name: "Quần áo", path: "/class1/clothes", bg: "#ff80ab" },
    { name: "Ngoại hình", path: "/class1/appearance", bg: "#ff80ab" },
    { name: "Khuôn mặt", path: "/class1/face", bg: "#ff80ab" },
  ],
  class5: [
    { name: "Xin chào", path: "/class1/Hello", image: "/img/animal.jpg" },
    { name: "Đồ dùng học tập", path: "/class1/school-things", bg: "#b2ff59" },
    { name: "Màu sắc", path: "/class1/colors", bg: "#80d8ff" },
    { name: "Gia đình", path: "/class1/family", bg: "#ff80ab" },
    { name: "Số đếm", path: "/class1/number", bg: "#ff80ab" },
    { name: "Quần áo", path: "/class1/clothes", bg: "#ff80ab" },
    { name: "Ngoại hình", path: "/class1/appearance", bg: "#ff80ab" },
    { name: "Khuôn mặt", path: "/class1/face", bg: "#ff80ab" },
  ],
};

module.exports = TopicByClass;
